version: 2

builds:
  - skip: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: petros0
    name: supadata-go
  draft: false
  prerelease: auto
  name_template: "{{.Tag}}"
